packages:
  - client
  - server

allowBuilds:
  esbuild: set this to true or false
  simple-git-hooks: true

blockExoticSubdeps: true

minimumReleaseAge: 1440

overrides:
  esbuild@>=0.17.0 <0.28.1: ^0.28.1
  esbuild@>=0.27.3 <0.28.1: ^0.28.1
  markdown-it@>=13.0.0 <14.1.1: '>=14.1.1'

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080

dedupePeers: true

minimumReleaseAgeExclude:
  - esbuild@0.28.1
