packages:
  - client
  - server

allowBuilds:
  simple-git-hooks: true

blockExoticSubdeps: true

minimumReleaseAge: 1440

overrides:
  markdown-it@>=13.0.0 <14.1.1: '>=14.1.1'

trustPolicy: no-downgrade

trustPolicyIgnoreAfter: 10080
