name: Vulnerability Audit
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/audit.yml'
      - pnpm-lock.yaml
  pull_request:
    paths:
      - '.github/workflows/audit.yml'
      - pnpm-lock.yaml
  schedule:
    - cron: '00 23 * * *' # Runs at midnight UTC every day
permissions:
  contents: read
jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Install Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Check Node.js version for vulnerabilities
        run: pnpm dlx is-my-node-vulnerable
      - name: Check dependencies for vulnerabilities
        run: node --run test:audit
