name: Vulnerability Audit
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/audit.yml'
      - pnpm-lock.yaml
  pull_request:
    paths:
      - '.github/workflows/audit.yml'
      - pnpm-lock.yaml
  schedule:
    - cron: '00 23 * * *' # Runs at midnight UTC every day
permissions:
  contents: read
jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Node.js & pnpm
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # v3.0.0
      - name: Check Node.js version for vulnerabilities
        run: pnpm dlx is-my-node-vulnerable
      - name: Check dependencies for vulnerabilities
        run: node --run test:audit
