name: Vulnerability Audit
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/audit.yml'
      - pnpm-lock.yaml
  pull_request:
    paths:
      - '.github/workflows/audit.yml'
      - pnpm-lock.yaml
  schedule:
    - cron: '00 23 * * *' # Runs at midnight UTC every day
permissions:
  contents: read
jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
      - name: Install Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Check Node.js version for vulnerabilities
        run: pnpm dlx is-my-node-vulnerable
      - name: Check dependencies for vulnerabilities
        run: node --run test:audit
