name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Install asdf
        uses: asdf-vm/actions/setup@v1
      - name: Cache asdf
        id: asdf-cache
        uses: actions/cache@v3
        with:
          path: ~/.asdf
          key: asdf-${{ hashFiles('**/.tool-versions') }}
      - name: Install asdf tools
        if: steps.asdf-cache.outputs.cache-hit != 'true'
        uses: asdf-vm/actions/install@v1
      - name: Cache pnpm modules
        uses: actions/cache@v3
        env:
          cache-name: cache-pnpm-modules
        with:
          path: ~/.pnpm-store
          key: pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --ignore-scripts
      - name: Run core tests
        run: pnpm test
        env:
          FORCE_COLOR: 2
      - name: Run projects tests
        run: pnpm -r test
        env:
          FORCE_COLOR: 2
