name: Update
on:
  schedule:
    - cron: '0 0,12 * * *'
permissions:
  contents: none
jobs:
  update:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Update dependencies
        run: pnpm update -r caniuse-lite browserslist browserslist-lint baseline-browser-mapping
      - name: Check dependencies
        id: changes
        run: node ./scripts/check-changes.js
      - name: Setup git config
        if: steps.changes.outputs.changes
        run: |
          git config user.name "Andrey Sitnik"
          git config user.email "andrey@sitnik.es"
      - name: Run tests
        if: steps.changes.outputs.changes
        run: pnpm test
      - name: Commit changes
        if: steps.changes.outputs.changes
        run: |
          git add pnpm-lock.yaml **/package.json
          git commit -m "Update caniuse-lite and browserslist"
      - name: Push changes
        if: steps.changes.outputs.changes
        run: git push --follow-tags
